# These are supported funding model platforms

github:  [hnicolus]
patreon: nicolasmaluleke
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.buymeacoffee.com/nicolasmaluleke', 'paypal.me/nicolasmaluleke']
