# These are supported funding model platforms

github:  [hnicolus]
patreon: nicolasmaluleke
custom:["https://www.buymeacoffee.com/nicolasmaluleke", "https://www.paypal.me/nicolasmaluleke"]
tidelift: nuget/Tawkto.OrchardCore
